# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

def pod_modules

  pod 'SnapKit'
  pod 'SwiftyUserDefaults'

end

target 'ToDoList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ToDoList
  pod_modules

  target 'ToDoListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ToDoListUITests' do
    # Pods for testing
  end

end
